In [21]:
import torch
import numpy as np

In [9]:
x = torch.empty(2,3)
print(x)
x = torch.rand(2, 2)
print(x)
x = torch.zeros(2, 2)
print(x)
x = torch.ones(2, 2)
print(x)
x = torch.ones(2, 2, dtype=int)
print(x)
x = torch.tensor([2.5, 5])
print(x)

tensor([[6.8984e-07, 2.0451e+23, 5.2356e+22],
        [1.3167e-08, 4.0105e-11, 7.1450e+31]])
tensor([[0.7386, 0.1621],
        [0.8907, 0.7988]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1, 1],
        [1, 1]])
tensor([2.5000, 5.0000])


In [13]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(f'x = {x}')
print(f'y = {y}')

## element wise + - * /
z = x+y; print(z)
y.add_(x); print(f'y = {y}')

x = tensor([[0.1614, 0.6472],
        [0.0427, 0.6820]])
y = tensor([[0.7286, 0.1800],
        [0.8691, 0.2972]])
tensor([[0.8900, 0.8272],
        [0.9118, 0.9792]])
y = tensor([[0.8900, 0.8272],
        [0.9118, 0.9792]])


In [17]:
x = torch.rand(5, 3)
print(x)
print(x[1, :])
print(x[1, 1].item())

tensor([[0.3783, 0.2054, 0.0563],
        [0.5547, 0.7158, 0.2765],
        [0.4358, 0.6269, 0.3676],
        [0.9273, 0.9130, 0.8496],
        [0.8604, 0.8897, 0.3726]])
tensor([0.5547, 0.7158, 0.2765])
0.7157912254333496


In [20]:
x = torch.rand(4, 4)
print(f'x = {x}')

y = x.view(2, 8)
print(f'y = {y}')

x = tensor([[0.6592, 0.3086, 0.1327, 0.1970],
        [0.5359, 0.8124, 0.4346, 0.3007],
        [0.4051, 0.8519, 0.4880, 0.8774],
        [0.0347, 0.8628, 0.1404, 0.9077]])
y = tensor([[0.6592, 0.3086, 0.1327, 0.1970, 0.5359, 0.8124, 0.4346, 0.3007],
        [0.4051, 0.8519, 0.4880, 0.8774, 0.0347, 0.8628, 0.1404, 0.9077]])


In [28]:
a = torch.ones(5)
print(f'a = {a}, type={type(a)}')

b = a.numpy()
print(f'b = {b}, type={type(b)}')

"""
If the tensor is on the cpu then both the tensor and the numpy array
will share the same memory location. Hence the modification of the 
original (tensor or numpy array) will modify the copy in the same way.
"""
a.add_(1)
print(f'a = {a}')
print(f'b = {b}')

b = b*2
print(f'a = {a}')
print(f'b = {b}')

b = np.ones(5)
a = torch.from_numpy(b)
print(f'a = {a}')
print(f'b = {b}')

b+=1
print(f'a = {a}')
print(f'b = {b}')



a = tensor([1., 1., 1., 1., 1.]), type=<class 'torch.Tensor'>
b = [1. 1. 1. 1. 1.], type=<class 'numpy.ndarray'>
a = tensor([2., 2., 2., 2., 2.])
b = [2. 2. 2. 2. 2.]
a = tensor([2., 2., 2., 2., 2.])
b = [4. 4. 4. 4. 4.]
a = tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
b = [1. 1. 1. 1. 1.]
a = tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
b = [2. 2. 2. 2. 2.]
