In [2]:
import torch
import numpy as np

In [20]:
x = torch.randn(3, requires_grad=True)
print(f'x = {x}')

y = x+2; print(f'y = {y}')

z = y*y*2; print(f'z = {z}')
# z = z.mean(); print(f'z = {z}')
v = torch.tensor([0.1, 1., 0.001], dtype=torch.float32)

z.backward(v)
print(f'z = {z}')
# grad_x = x.grad; print(f'grad_x = {grad_x}')


x = tensor([ 0.8347, -1.0032, -1.3366], requires_grad=True)
y = tensor([2.8347, 0.9968, 0.6634], grad_fn=<AddBackward0>)
z = tensor([16.0711,  1.9874,  0.8801], grad_fn=<MulBackward0>)
z = tensor([16.0711,  1.9874,  0.8801], grad_fn=<MulBackward0>)


In [26]:
x = torch.randn(3, requires_grad=True)
print(f'x = {x}')

# x.requires_grad_(False)
# y = x.detach()
with torch.no_grad():
    y = x+2
    print(y)

# print(f'x = {x}')
# print(f'y = {y}')

x = tensor([-0.6777, -1.2178, -1.1983], requires_grad=True)
tensor([1.3223, 0.7822, 0.8017])


In [31]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()
    grad = weights.grad

    print(grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

opt = torch.optim.SGD(weights, lr=0.01)
opt.step()
opt.zero_grad()
