In [1]:
import torch
import torch.nn as nn

In [7]:
class Model(nn.Module):
    def __init__(self, n_inp_feat):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_inp_feat, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred


model = Model(n_inp_feat=6)
for param in model.parameters():
    print(param)
# train your model ...

## Saving the model ##
# method 1 #
# FILE = "model.pth"
# torch.save(model, FILE)

# model_load = torch.load(FILE)
# model_load.eval()

# for param in model_load.parameters():
#     print(param)


# method 2 - recommended #
FILE = "model_2.pth"
torch.save(model.state_dict(), FILE)

model_load = Model(n_inp_feat=6)
model_load.load_state_dict(torch.load(FILE))
model_load.eval()

for param in model_load.parameters():
    print(param)


Parameter containing:
tensor([[-0.3065,  0.0649,  0.1454,  0.3458, -0.1490, -0.2314]],
       requires_grad=True)
Parameter containing:
tensor([-0.2677], requires_grad=True)
Parameter containing:
tensor([[-0.3065,  0.0649,  0.1454,  0.3458, -0.1490, -0.2314]],
       requires_grad=True)
Parameter containing:
tensor([-0.2677], requires_grad=True)


Parameter containing:
tensor([[-0.1747,  0.2953, -0.0830,  0.0522,  0.0759,  0.1127]],
       requires_grad=True)
Parameter containing:
tensor([-0.2670], requires_grad=True)
